name: training
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.1.4
  pedantic: ^1.11.1
  velocity_x: ^3.3.0
  device_preview: ^0.7.1
  font_awesome_flutter: ^9.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/top_menus/
    - assets/popular_foods/
    - assets/best_foods/
